import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
